# Generated by Django 2.1.7 on 2019-02-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default='2019-2-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Shop'),
        ),
    ]
