# Generated by Django 2.1.7 on 2019-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190217_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In progress'), ('Completed', 'completed')], max_length=25),
        ),
    ]
