# Generated by Django 2.1.7 on 2019-02-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190218_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
    ]
