# Generated by Django 2.1.7 on 2019-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_orders_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='item',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='item',
            field=models.ManyToManyField(to='app1.Product'),
        ),
    ]
