# Generated by Django 2.1.7 on 2019-03-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20190302_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount_paid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
